# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CreditCardRewards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CreditCardRewards
  pod 'Firebase/Database'
  pod 'Kingfisher'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  

  target 'CreditCardRewardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CreditCardRewardsUITests' do
    # Pods for testing
  end

end
